# Generated by pip2nix 0.8.0.dev1
# See https://github.com/nix-community/pip2nix

{ pkgs, fetchurl, fetchgit, fetchhg }:

self: super: {
  "pyperclip3" = super.buildPythonPackage rec {
    pname = "pyperclip3";
    version = "0.4.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/56/09/8f71b75e1019670322fa55a3b94e01af8b8097dbd039331582a56a785999/pyperclip3-0.4.1-py3-none-any.whl";
      sha256 = "0lclfzmz365fq6qj88aplkn35rxz5kvwcb6p23s170w50h52jca6";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
}
