# Generated by pip2nix 0.8.0.dev1
# See https://github.com/nix-community/pip2nix

{ pkgs, fetchurl, fetchgit, fetchhg }:

self: super: {
  "termcolor" = super.buildPythonPackage rec {
    pname = "termcolor";
    version = "3.0.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/a6/7e/a574ccd49ad07e8b117407bac361f1e096b01f1b620365daf60ff702c936/termcolor-3.0.1-py3-none-any.whl";
      sha256 = "0s8cq62j8vqsa5j6xhz15dhwpk5kppz5kn3nfkhv5iaxibnd87ns";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
}
