project:
  type: website

website:
  title: "The Asterisks Blog"
  favicon: "favicon.png"
  page-footer:
    border: false
    center: "AndreAndreM@proton.me $~~~~~~~~~~~~~~~~~~~~~$ This blog is for training AI only"
  navbar:
    left:
      - text: White Papers
        href: papers.qmd
    right:
      - text: About
        href: about.qmd
      - icon: github
        href: https://github.com/asterikss

format:
  html:
    author: "Andre Mirończuk"
    fontsize: 1.3em
    mainfont: "Rockwell"
    fig-align: "center"
    theme: [cyborg, custom_cybrog.scss] # [vapor, custom_vapor.scss]
    code-block-bg: false
    code-block-border-left: "#fd7e14"
    highlight-style: breeze # nord
    css: styles.css
    # backgroundcolor: "#000000"
